### DISCUSSION TITLE
set --log-level by ENV in docker

### DISCUSSION THREAD

**Discussion by massimiliano-cannata** [cybertec-postgresql/pg_timetable#601] [Q&A] [answered]
Sorry of the question is dummy,
I'm using the docker-compose and I was wandering if there's an easy way to setup:
--log-level=[debug|info|error]               Verbosity level for stdout and log file (default: info)
--log-database-level=[debug|info|error|none]                Verbosity level for database storing (default: info)
      
by using an environment variables with appropriate value.

like:
PGTT_LOG_LEVEL
PGTT_LOG_DB_LEVEL

Best and compliment for the great project!

Maxi

**Comment by pashagolub** [comment]
Can you show us what do you have already? Any `docker-compose.yaml`?

**Comment by pashagolub** [comment]
I believe you want to use this trick: https://stackoverflow.com/questions/40447029/docker-compose-environment-variable-for-command

So the main idea is you're escaping container environment variable and the use it's value in the command line

**Comment by massimiliano-cannata** [comment]
Hi,
This is my docker-compos.yml

```
pgtt:
    image: "cybertecpostgresql/pg_timetable:latest"
    networks:
      - app-tier
    depends_on:
      - wns_db
    volumes:
      - ./pgtt/scripts:/usr/local/bin
      - ./wnslib:/wnslib
    environment:
      PGTT_CLIENTNAME: cron
      PGTT_PGHOST: ${PG_HOST}
      PGTT_PGPORT: ${PG_DB_PORT}
      PGTT_PGDATABASE: ${PG_DB_NAME}
      PGTT_PGUSER: ${PG_USER}
      PGTT_PGPASSWORD: ${PG_PASSWORD}
```
It would be nice to set PGTT_LOG_LEVEL: debug and have the container run with debug log level

So far to overcome I have created a Dockerfile (since i needed to run python code) and override ENTRYPOINT like this:

```
FROM cybertecpostgresql/pg_timetable:latest
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

# install dependencies to the local user directory (eg. /root/.local)
COPY requirements.txt .
RUN pip install --user -r requirements.txt

ENTRYPOINT ["/pg_timetable", "--log-level=debug"]
```
and have changed the compose to:

```
pgtt:
    # image: "cybertecpostgresql/pg_timetable:latest"
    build:
      context: pgtt
      dockerfile: Dockerfile
    networks:
      - app-tier
    depends_on:
      - wns_db
    volumes:
      - ./pgtt/scripts:/usr/local/bin
      - ./wnslib:/wnslib
    environment:
      PGTT_CLIENTNAME: cron
      PGTT_PGHOST: ${PG_HOST}
      PGTT_PGPORT: ${PG_DB_PORT}
      PGTT_PGDATABASE: ${PG_DB_NAME}
      PGTT_PGUSER: ${PG_USER}
      PGTT_PGPASSWORD: ${PG_PASSWORD}
```

**Reply by pashagolub** [reply, marked as answer]
Can you just use 
```
pgtt:
    image: "cybertecpostgresql/pg_timetable:latest"
    networks:
      - app-tier
    depends_on:
      - wns_db
    volumes:
      - ./pgtt/scripts:/usr/local/bin
      - ./wnslib:/wnslib
    command:
        ["/pg_timetable", "--log-level=debug"]
    environment:
      PGTT_CLIENTNAME: cron
      PGTT_PGHOST: ${PG_HOST}
      PGTT_PGPORT: ${PG_DB_PORT}
      PGTT_PGDATABASE: ${PG_DB_NAME}
      PGTT_PGUSER: ${PG_USER}
      PGTT_PGPASSWORD: ${PG_PASSWORD}
```
?
